name       : modelio
version    : 3.7.0
release    : 1
source     :
    - http://forge.modelio.org/attachments/download/19914/modelio_sources_3.7.0.zip : b9f27cc4a8ec46a2805e3eab70dee86c7d0f963b98181caebc39aca55ab7babd
license    : GPL-3.0
component  : programming.tools
summary    : UML modeling tool
description: |
    Modelio is an open source UML modeling tool.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mkdir m2
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    cd AGGREGATOR
    mvn package
install    : |
    install -d $installdir/usr/share/modelio
    cp -R eclipse.resources/products/target/products/org.modelio.product/linux/gtk/x86_64/Modelio*/* $installdir/usr/share/modelio/
    install -d $installdir/usr/bin
    ln -s /usr/share/modelio/modelio $installdir/usr/bin/modelio
    install -d $installdir/usr/share/icons/hicolor/scalable/apps/
    cp -R $installdir/usr/share/modelio/icon.xpm $installdir/usr/share/icons/hicolor/scalable/apps/modelio.xpm
    install -d $installdir/usr/share/mime/packages
    cp $pkgfiles/modelio.xml $installdir/usr/share/mime/packages/
    install -D -m 00644 $pkgfiles/modelio.desktop $installdir/usr/share/applications/modelio.desktop
