name       : modelio
version    : 4.1.0
release    : 6
source     :
    - https://github.com/ModelioOpenSource/Modelio/archive/v4.1.0.tar.gz : 5e48fb8ed3bbc18b475a99b864caee5f677f1afca736356389a9ab57704d48a2
license    : GPL-3-or-later
component  : programming.tools
summary    : UML modeling tool
description: |
    Modelio is an open source UML modeling tool.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - libwebkit-gtk
    - openjdk-11
setup      : |
    # modelio uses a lot of fragile undefined maven behavior. this patch combats this. ask @serebit for help if this doesn't work 
    cp dev-platform/compilation-env/javadesigner.jar modelio/app/app.editors.richnote.libreoffice/lib/
    mkdir modelio/app/app.editors.richnote.microsoft/lib
    cp dev-platform/compilation-env/javadesigner.jar modelio/app/app.editors.richnote.microsoft/lib/
    cp dev-platform/rcp-target/rcp-eclipse/eclipse/plugins/org.eclipse.swt.win32.win32.x86_3*.jar modelio/app/app.editors.richnote.microsoft/lib/eclipse.jar
    %patch -p1 < $pkgfiles/0001-Fix-building-with-maven-and-java-11.patch
build      : |
    cd AGGREGATOR
    mvn -Dmaven.repo.local=$workdir/.m2 package
install    : |
    install -dm00755 $installdir/usr/share/modelio
    cp -a products/target/products/org.modelio.product/linux/gtk/x86_64/Modelio*/* $installdir/usr/share/modelio
    install -d $installdir/usr/bin
    ln -s /usr/share/modelio/modelio $installdir/usr/bin/modelio
    install -d $installdir/usr/share/pixmaps
    cp -a $installdir/usr/share/modelio/icon.xpm $installdir/usr/share/pixmaps/modelio.xpm
    install -dm00755 $installdir/usr/share/mime/packages
    cp $pkgfiles/modelio.xml $installdir/usr/share/mime/packages
    install -Dm00644 $pkgfiles/modelio.desktop -t $installdir/usr/share/applications

    # Set the correct OpenJDK
    sed -i '/-vmargs/i -vm\n/usr/lib64/openjdk-8/bin/java' $installdir/usr/share/modelio/modelio.ini
