name       : modelio
version    : 3.8.0
release    : 3
source     :
    - http://forge.modelio.org/attachments/download/21499/modelio_sources_3.8.0.zip : 983620501b671ffb0981e0672d5f665df4c00fb3bcaf1fc55c45222cc4031578
license    : GPL-3.0
component  : programming.tools
summary    : UML modeling tool
description: |
    Modelio is an open source UML modeling tool.
networking : yes
builddeps  :
    - apache-maven
rundeps    :
    - openjdk-8
build      : |
    mkdir m2
    export MAVEN_OPTS="-Dmaven.repo.local=./m2"
    cd AGGREGATOR
    mvn package
install    : |
    install -d $installdir/usr/share/modelio
    cp -R eclipse.resources/products/target/products/org.modelio.product/linux/gtk/x86_64/Modelio*/* $installdir/usr/share/modelio/
    install -d $installdir/usr/bin
    ln -s /usr/share/modelio/modelio $installdir/usr/bin/modelio
    install -d $installdir/usr/share/pixmaps
    cp -R $installdir/usr/share/modelio/icon.xpm $installdir/usr/share/pixmaps/modelio.xpm
    install -d $installdir/usr/share/mime/packages
    cp $pkgfiles/modelio.xml $installdir/usr/share/mime/packages/
    install -D -m 00644 $pkgfiles/modelio.desktop $installdir/usr/share/applications/modelio.desktop
